### PR TITLE
Add some basic examples

### PR DESCRIPTION
**Pull request by insanity54**
I think basic examples are necessary to grasp usage. When learning aedes, I didn't see any non-cluster examples in the examples dir so I had to dig through the issue tracker to find some.

This PR addresses https://github.com/moscajs/aedes/issues/187. There are some good examples in that issue thread, which I've copied and placed in the examples directory.

### CODE REVIEW

**Comment by robertsLando** [comment]
Isn't this enough: https://github.com/moscajs/aedes/blob/main/docs/Examples.md ?

**Comment by insanity54** [comment]
I don't think so. It's missing an example client.

**Comment by robertsLando** [comment]
The client example depends on the client library you use, for example mqttjs provides it's own example in [docs](https://github.com/mqttjs/MQTT.js#example)

**Comment by insanity54** [comment]
Okay, I understand. Maybe the examples in this PR is out of scope of aedes server.

I still think aedes has a documentation issue; I would like to improve them. I'm going to open a separate issue.

**Pull request closed without merging**
