### PR TITLE
fix(types): add brokers interface

### PR DESCRIPTION
**Pull request by getlarge**
Add missing interface

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]
LGTM

**Review by mcollina — CHANGES_REQUESTED** [review]
tests are missing

**Comment by getlarge** [comment]
@mcollina i don't see what could be added in `test/types/index.ts`.
Something like : `const { brokers } = broker` would be enough ?

**Comment by mcollina** [comment]
Yes!

**Comment by mcollina** [comment]
You can also use expectType assertion from tsd

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by robertsLando** [comment]
@getlarge Wait until also PR #584 get merged for a new release

**Comment by gnought** [comment]
@getlarge It is suppose `broker` property in Aedes is for internal usage. Any reasons behind / user cases are there to require the `broker` interface?

**Comment by getlarge** [comment]
@gnought It's related to that [PR](https://github.com/moscajs/aedes-persistence/pull/76/files), aedes-persistence is using `Brokers` interface.

**Pull request merged**
