### PR TITLE
fix: typescript types issues

### PR DESCRIPTION
**Pull request by robertsLando**
Also renamed `Aedes` alias function `Server` to `createBroker`

### CODE REVIEW

**Comment by erwinschrodinger1** [comment]
Still having this issue:
```No overload matches this call.
  Overload 1 of 2, '(connectionListener?: (socket: Socket) => void): Server', gave the following error.
    Argument of type '(stream: Connection, request: IncomingMessage) => Client' is not assignable to parameter of type '(socket: Socket) => void'.
  Overload 2 of 2, '(options?: ServerOpts, connectionListener?: (socket: Socket) => void): Server', gave the following error.
    Type '(stream: Connection, request: IncomingMessage) => Client' has no properties in common with type 'ServerOpts'.ts(2769)
```

Code:
``````
import Aedes from 'aedes'
import net from 'net'
const aedes = new Aedes()
const mqttServer: net.Server = net.createServer(aedes.handle)
mqttServer.listen(MQTTPORT, () => {
    console.log(
        `Aedes MQTT broker started and listening on MQTTPORT ${MQTTPORT}`
    );
});
``````

Used packages:
```"aedes": "^0.49.0"```
```"net": "^1.0.2"```

**Comment by robertsLando** [comment]
PR?

**Comment by erwinschrodinger1** [comment]
I haven't created a PR yet. You can assign this to me. I would do it asap.

**Comment by robertsLando** [comment]
No worries :)

**Pull request merged**
