### PR TITLE
[WIP] Github actions for cross persistence/mqemitter tests #357

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Comment by robertsLando** [comment]
Now need to replace all `aedes()` in test with an helper method that adds persistences/mqemitters

**Comment by mcollina** [comment]
Most of the tests are unit. We need a new batch of tests that works treating aedes as a black box.

IMHO, I'd place them in another repo.

**Comment by robertsLando** [comment]
@mcollina Ok does it means a complete rewrite of tests?

**Comment by mcollina** [comment]
Not a rewrite, _new_ tests.

**Comment by robertsLando** [comment]
Yes I used the wrong word but that is what I meant

**Comment by robertsLando** [comment]
@mcollina Would you mind consider a part of this PR? I could remove the actions.yml and the process.env vars and keep the centralized aedes instance creation using helper method. This may be useful in future?

**Comment by mcollina** [comment]
I don't think so. The current tests are too tied and this adds unnecessary complexity.

**Pull request closed without merging**
