### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Comment by robertsLando** [comment]
@mcollina Would you like issue templates to be added?

**Comment by mcollina** [comment]
I would create those org-wise in the .github repo.

**Comment by robertsLando** [comment]
Is it possibile? 

Daniel

**Comment by mcollina** [comment]
https://github.com/fastify/.github
Il 6 feb 2020, 22:37 +0100, Daniel Lando <notifications@github.com>, ha scritto:
> Is it possibile?
>
> Daniel
>

**Pull request closed without merging**
