### PR TITLE
fix: catch writeToStream errors

### PR DESCRIPTION
**Pull request by robertsLando**
@mcollina this should fix unhandled expections when a non-valid packet is write to stream

### CODE REVIEW

**Comment by robertsLando** [comment]
@mcollina I'm :+1: for the test but why this isn't working? 

```js
// Catch invalid packet writeToStream errors
test('reject client requested for unsupported protocol version', function (t) {
  t.plan(3)

  const broker = aedes()
  t.tearDown(broker.close.bind(broker))

  const s = setup(broker)

  var packet = [
    16, 22, 0, 4, 77, 81, 84, 84,
    4, 2, 0, 0, 0, 10, 109, 121,
    99, 108, 105, 101, 110, 116, 105, 100,
    85, 0
  ]

  s.inStream.write(Buffer.from(packet))

  s.outStream.on('data', function (packet) {
    t.fail('no data sent')
  })
  broker.on('connectionError', function (client, err) {
    t.equal(client.version, null)
    t.equal(err.message, 'Unknown command')
    t.equal(broker.connectedClients, 0)
  })
})
```

I mean, it works as test but it doesn't make that function throw

**Comment by mcollina** [comment]
I mean require the function directly and mock everything.

**Comment by robertsLando** [comment]
@mcollina I tried even that way and I'm not able to reproduce the problem, maybe I'm missing something

**Comment by mcollina** [comment]
You should use proxyquire to mock writeToStream.

**Comment by robertsLando** [comment]
@mcollina I saw that if there are errors or client is no connecting/connected the write never calls `done` is this correct or should we also call `done(err)`?

**Comment by mcollina** [comment]
> I saw that if there are errors or client is no connecting/connected the write never calls done is this correct or should we also call done(err)?

I do not know.

**Pull request merged**
