### PR TITLE
Extend coverage to 100%

### PR DESCRIPTION
**Pull request by robertsLando**
#428

### CODE REVIEW

**Comment by gnought** [comment]
@robertsLando We can't catch the error, as mqtt-parser has already filtered out all unknown verb, but It is safe to have a check in `lib/handlers/index.js`. That what I include in the next branch https://github.com/gnought/aedes/blob/next/test/basic.js#L293

**Comment by robertsLando** [comment]
With this we should be 100% covered by tests :tada:

**Comment by robertsLando** [comment]
@gnought Could you review this?

**Comment by gnought** [comment]
@robertsLando I have checkout the coverage branch, but I can't get 100% coverage by `npm run unit:report`

**Comment by robertsLando** [comment]
@gnought It give 100% to me. Check https://coveralls.io/builds/28705089

**Comment by robertsLando** [comment]
@mcollina Could you review this?

**Pull request merged**
