### PR TITLE
WIP: shared subscriptions

### PR DESCRIPTION
**Pull request by robertsLando**
This is a work in progress for the feature. I would like to know your opinion about this idea and if this could be the right direction or not. @gnought @mcollina 

#228

### CODE REVIEW

**Comment by robertsLando** [comment]
@mcollina So what should be the way? Suggestions?

**Comment by mcollina** [comment]
It needs to be architected/investigated, I’m basically stating requirements. I currently do not have time for doing so in the near future.

A practical way is to have a “plugin” built on top of Redis Streams. This might have significant limitation related to how #/+ work.

A more complex solution is to publish the “active” shared subscription for each peer in the broker metadata, and have the message being routed to a different broker if the current one does not have a an active shared subscription for that topic.

**Comment by robertsLando** [comment]
Could my actual implementation work in a single-instance model at least? 

About your answer I think the best way would be to add shared subscriptions to aedes-persistence or it becomes hard to handle. I was thinking about a solution using `$SYS` topics but I think it becomes complex and has very bad efficiency

**Comment by gnought** [comment]
good try.
imo. aedes is a multi process model, we need to make it flexile rather than implemented in single-instance.

**Comment by robertsLando** [comment]
@gnought Could we speak about a possible solution for this? I think a possible soulutions could be:

Once we receive a shared subscriuption we add the subscription to persistence with a `created` date (set to now) an a `lastUpdate` date set to null. Before each delivery the client will check in the persistence for the shared subscription to that topic with the lower lastUpdate and if the subscription returned has his clientId he delivers the packet and update his subscription `lastUpdate`

Should this work? Thoughts?

**Comment by gnought** [comment]
There may be more work to do before that, and make the whole picture be clear. Would you mind to extract out interfaces that other aedes persistence should implement to, it is nicer if we have a typing in aedes-persistence.

**Comment by robertsLando** [comment]
@gnought Check https://github.com/moscajs/aedes-persistence/pull/48 Than I will add new methods

**Comment by robertsLando** [comment]
@gnought I close this and start working on the new one

**Comment by abhargav7** [comment]
@robertsLando  does closing means you are creating a PR from new branch sooner, or case is closed :)
Thanks for supporting this.

**Pull request closed without merging**
