### PR TITLE
Fix tests to proper handling of new socketErrors introducing in mqtt client v4

### PR DESCRIPTION
**Pull request by gnought**
Further fix on PR https://github.com/moscajs/aedes/pull/479

We closed broker and server just after closing publisher and subscriber.
https://github.com/moscajs/aedes/blob/de17e01f23ed9882474e489d7d9ae8af44278e07/test/not-blocking.js#L201-L204

and it results `ECONNRESET`. It is a expected behaviour as we need to wait MQTT.js client to close connection gracefully.

ECONNRESET debug log
```
  mqttjs:client _cleanUp :: (mqttjs_e382a762) :: call _sendPacket with disconnect packet +0ms
  mqttjs:client _sendPacket :: (mqttjs_e382a762) ::  start +0ms
  mqttjs:client sendPacket :: packet: { cmd: 'disconnect' } +0ms
  mqttjs:client sendPacket :: emitting `packetsend` +0ms
  mqttjs:client sendPacket :: writing to stream +2ms
  mqttjs:client sendPacket :: writeToStream result true +0ms
  mqttjs:client sendPacket :: invoking cb +0ms
  mqttjs:client end :: (mqttjs_d12bcf91) +0ms
  mqttjs:client end :: cb? true +0ms
  mqttjs:client _clearReconnect : clearing reconnect timer +0ms
  mqttjs:client end :: (mqttjs_d12bcf91) :: immediately calling finish +0ms
  mqttjs:client end :: (mqttjs_d12bcf91) :: finish :: calling _cleanUp with force false +0ms
  mqttjs:client _cleanUp :: done callback provided for on stream close +0ms
  mqttjs:client _cleanUp :: forced? false +0ms
  mqttjs:client _cleanUp :: (mqttjs_d12bcf91) :: call _sendPacket with disconnect packet +0ms
  mqttjs:client _sendPacket :: (mqttjs_d12bcf91) ::  start +0ms
  mqttjs:client sendPacket :: packet: { cmd: 'disconnect' } +3ms
  mqttjs:client sendPacket :: emitting `packetsend` +0ms
  mqttjs:client sendPacket :: writing to stream +1ms
  mqttjs:client sendPacket :: writeToStream result true +0ms
  mqttjs:client sendPacket :: invoking cb +0ms
    ok 2 - messages sent
    ok 3 - messages received
  mqttjs:client streamErrorHandler :: error read ECONNRESET +8ms
  mqttjs:client streamErrorHandler :: emitting error +0ms
  mqttjs:client streamErrorHandler :: error read ECONNRESET +1ms
  mqttjs:client streamErrorHandler :: emitting error +0ms
```

Normal Log
```
  mqttjs:client _cleanUp :: (mqttjs_13852b93) :: call _sendPacket with disconnect packet +0ms
  mqttjs:client _sendPacket :: (mqttjs_13852b93) ::  start +0ms
  mqttjs:client sendPacket :: packet: { cmd: 'disconnect' } +0ms
  mqttjs:client sendPacket :: emitting `packetsend` +0ms
  mqttjs:client sendPacket :: writing to stream +0ms
  mqttjs:client sendPacket :: writeToStream result true +0ms
  mqttjs:client sendPacket :: invoking cb +0ms
  mqttjs:client end :: (mqttjs_3e515618) +0ms
  mqttjs:client end :: cb? true +0ms
  mqttjs:client _clearReconnect : clearing reconnect timer +0ms
  mqttjs:client end :: (mqttjs_3e515618) :: immediately calling finish +0ms
  mqttjs:client end :: (mqttjs_3e515618) :: finish :: calling _cleanUp with force false +0ms
  mqttjs:client _cleanUp :: done callback provided for on stream close +0ms
  mqttjs:client _cleanUp :: forced? false +0ms
  mqttjs:client _cleanUp :: (mqttjs_3e515618) :: call _sendPacket with disconnect packet +0ms
  mqttjs:client _sendPacket :: (mqttjs_3e515618) ::  start +0ms
  mqttjs:client sendPacket :: packet: { cmd: 'disconnect' } +1ms
  mqttjs:client sendPacket :: emitting `packetsend` +0ms
  mqttjs:client sendPacket :: writing to stream +1ms
  mqttjs:client sendPacket :: writeToStream result true +0ms
  mqttjs:client sendPacket :: invoking cb +0ms
    ok 2 - messages sent
    ok 3 - messages received
  mqttjs:client (mqttjs_3e515618)stream :: on close +7ms
  mqttjs:client flushVolatile :: deleting volatile messages from the queue and setting their callbacks as error function +1ms
  mqttjs:client stream: emit close to MqttClient +0ms
  mqttjs:client close :: connected set to `false` +0ms
  mqttjs:client close :: clearing connackTimer +0ms
  mqttjs:client close :: clearing ping timer +0ms
  mqttjs:client close :: calling _setupReconnect +0ms
  mqttjs:client _setupReconnect :: doing nothing... +0ms
  mqttjs:client end :: finish :: calling process.nextTick on closeStores +0ms
  mqttjs:client end :: closeStores: closing incoming and outgoing stores +0ms
  mqttjs:client end :: closeStores: emitting end +0ms
  mqttjs:client end :: closeStores: invoking callback with args +2ms
  mqttjs:client nop :: undefined +0ms
  mqttjs:client (mqttjs_13852b93)stream :: on close +0ms
  mqttjs:client flushVolatile :: deleting volatile messages from the queue and setting their callbacks as error function +1ms
  mqttjs:client stream: emit close to MqttClient +0ms
  mqttjs:client close :: connected set to `false` +0ms
  mqttjs:client close :: clearing connackTimer +0ms
  mqttjs:client close :: clearing ping timer +0ms
  mqttjs:client close :: calling _setupReconnect +0ms
  mqttjs:client _setupReconnect :: doing nothing... +0ms
  mqttjs:client end :: finish :: calling process.nextTick on closeStores +0ms
  mqttjs:client end :: closeStores: closing incoming and outgoing stores +0ms
  mqttjs:client end :: closeStores: emitting end +0ms
  mqttjs:client end :: closeStores: invoking callback with args +0ms
  mqttjs:client nop :: undefined +0ms
```

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by robertsLando — APPROVED** [review]
Lgtm

**Comment by robertsLando** [comment]
Snyk fails @gnought ?

**Comment by gnought** [comment]
@robertsLando May snky `security/snyk (robertsLando)` fails due to permission denied?

**Comment by robertsLando** [comment]
@gnought Based on what I saw it is caused by an old aedes version in examples package.json. The 0.41.0 was affected by a security issue that could cause DoS

**Pull request merged**
