### PR TITLE
fix: typings for publish event

### PR DESCRIPTION
**Pull request by barlock**
Fix the `publish` typings. Get them to match the docs:

https://github.com/moscajs/aedes/blob/main/docs/Aedes.md#event-publish

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]

**Comment by robertsLando** [comment]
@barlock Could you check failing tests?

**Comment by barlock** [comment]
They appear like intermittent failures to me as typings shouldn't affect runtime tests, that being said, I don't see obvious intermittent failure runs on main. I can't reproduce locally, I'm running the workflows on my fork to see if I can debug a little easier.

**Comment by robertsLando** [comment]
Yeah it seems strange to me too that tests are failing, could you try to change the [fail_fast](https://github.com/actions/setup-ruby/actions/runs/129752173/workflow#L18) on ci workflow to see if maybe only mac os tests are failing? I remember there was some flacky tests with macos (dunno why), if them are the only failing we could merge this anyway

**Comment by robertsLando** [comment]
LOL tests successfull now 🤷🏼‍♂️

**Comment by barlock** [comment]
Yeah, FWIW, in my fork, I retried this branch a few times and they were indeed flakey and _only_ on macOS. My host (Also macos) I've never seen this from so... No idea. 😅 

I'll have a similar PR up for aedes-persistence once I finish implementing a custom persistence so I'll have all of them. I've found a few type bugs similar to this one.

**Comment by robertsLando** [comment]
> I'll have a similar PR up for aedes-persistence once I finish implementing a custom persistence so I'll have all of them. I've found a few type bugs similar to this one.

Ok, thanks :)

**Pull request merged**
