### PR TITLE
Added opencollective links/images

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Comment by gnought** [comment]
@robertsLando Could I update the README.md to re-arrange some contents?

**Comment by robertsLando** [comment]
@gnought Sure !

**Comment by gnought** [comment]
We only have 29 contributors from github, why we get so many from opencollective link (https://opencollective.com/aedes/contributors.svg?width=890&button=false)?
Screenshot 2020-02-15 at 12 15 53 AM

**Comment by robertsLando** [comment]
I think also issues authors are counted

Daniel

**Comment by gnought** [comment]
the question is, should we count them?

**Comment by robertsLando** [comment]
I don’t know if there is a way to exclude them, if it is not good for you feel free to remove that 

Daniel

**Comment by robertsLando** [comment]
https://docs.opencollective.com/help/collectives/data-export

Based in this, you could set the limit to show to first 10/20 

Daniel

**Pull request merged**
